version: '3.7'
services:
  spark-livy:
    hostname: spark-livy
    container_name: spark-livy
    image: jungfrau70/spark-livy
    build:
      context: .
      dockerfile: Dockerfile.spark-livy
    command: ["sh", "-c", "/opt/livy/bin/livy-server"]
    volumes:
      - ./target:/target
      - ./data:/data
      - type: bind
        source: ./conf/
        target: /opt/livy/conf/
      - type: bind
        source: ./config/hosts
        target: /etc/hosts
    env_file:
      - spark-livy.env
    restart: always
    networks:
      netgroup:
        ipv4_address: 172.18.0.22
    ports:
      - '8998:8998'
    deploy:
      resources:
        limits:
          memory: 4g
volumes:
    shared-workspace:
        # name: "hadoop-distributed-file-system"
        # driver: local

networks:
  netgroup:
    name: netgroup
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

#env

